### ISSUE TITLE
Stacktrace (Generated by bedrock player?)

### ISSUE THREAD

**Issue by USBCharger** [erikzimmermann/TradeSystem#458]
Getting a stacktrace - believe it's caused by a bedrock player.

`[22:57:34 INFO]: UUID of player .Default96863627 is 00000000-0000-0000-0009-01ffbaa57c69
[22:57:34 WARN]: Unexpected token END OF FILE at position 0.
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:220)
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:64)
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:57)
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.Skin.getElement(Skin.java:179)
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.GameProfileUtils.extractSkinId(GameProfileUtils.java:44)
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.sync(PublishSkinListener.java:31)
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.sync(PublishSkinListener.java:24)
[22:57:34 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.onJoin(PublishSkinListener.java:20)
[22:57:34 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1089.execute(Unknown Source)
[22:57:34 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[22:57:34 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[22:57:34 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:57:34 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:57:34 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:57:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[22:57:34 WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:339)
[22:57:34 WARN]:        at net.minecraft.server.network.LoginListener.a(LoginListener.java:202)
[22:57:34 WARN]:        at net.minecraft.server.network.LoginListener.d(LoginListener.java:183)
[22:57:34 WARN]:        at net.minecraft.server.network.LoginListener.c(LoginListener.java:85)
[22:57:34 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:611)
[22:57:34 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:234)
[22:57:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1614)
[22:57:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[22:57:34 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[22:57:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[22:57:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:57:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:57:34 INFO]: .Default96863627[/59.41.93.114:40332] logged in with entity id 11208 at ([world]2639.9265, 63.0, -832.45715)
[22:57:35 WARN]: Unexpected token END OF FILE at position 0.
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:220)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:64)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:57)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.Skin.getElement(Skin.java:179)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.GameProfileUtils.extractSkinId(GameProfileUtils.java:44)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.sync(PublishSkinListener.java:31)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.lambda$sync$1(PublishSkinListener.java:34)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[22:57:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:57:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:57:35 WARN]: Unexpected token END OF FILE at position 0.
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:220)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:64)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:57)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.Skin.getElement(Skin.java:179)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.GameProfileUtils.extractSkinId(GameProfileUtils.java:44)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.sync(PublishSkinListener.java:31)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.lambda$sync$1(PublishSkinListener.java:34)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[22:57:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:57:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:57:35 WARN]: Unexpected token END OF FILE at position 0.
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:220)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:64)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:57)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.Skin.getElement(Skin.java:179)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.GameProfileUtils.extractSkinId(GameProfileUtils.java:44)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.sync(PublishSkinListener.java:31)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.lambda$sync$1(PublishSkinListener.java:34)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[22:57:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:57:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:57:35 WARN]: Unexpected token END OF FILE at position 0.
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:220)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:64)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.tools.io.lib.JSONParser.parse(JSONParser.java:57)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.Skin.getElement(Skin.java:179)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.lib.codingapi.player.data.GameProfileUtils.extractSkinId(GameProfileUtils.java:44)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.sync(PublishSkinListener.java:31)
[22:57:35 WARN]:        at TradeSystem.jar//de.codingair.tradesystem.spigot.trade.listeners.PublishSkinListener.lambda$sync$1(PublishSkinListener.java:34)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:57:35 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[22:57:35 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[22:57:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[22:57:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

Discord: Rockethub

**Comment by AlexanderMandera** [comment]
Should be fixed with merging the PR.
Maybe something will need to be implemented for Floodgate Skin Support,
but this is up to @erikzimmermann
