### ISSUE TITLE
I keep getting this warning when I turn on the firewall.

### ISSUE THREAD

**Issue by ejdzeys** [erikzimmermann/TradeSystem#484]
I keep getting this warning ever since I turned on the firewall. It gives the warning once every hour.

[15:31:44] [Craft Scheduler Thread - 2485/WARN]: [TradeSystem] Plugin TradeSystem v2.4.0 generated an exception while executing task 161
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseString(java.lang.String)'
	at de.codingair.tradesystem.spigot.utils.updates.UpdateNotifier.read(UpdateNotifier.java:41) ~[?:?]
	at de.codingair.tradesystem.spigot.TradeSystem.lambda$startUpdateNotifier$2(TradeSystem.java:225) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by erikzimmermann** [comment]
This is already fixed. You can download the latest version from here: https://github.com/erikzimmermann/TradeSystem/suites/15384458503/artifacts/878446560
