### ISSUE TITLE
Warn when editing layouts in console

### ISSUE THREAD

**Issue by Regomy** [erikzimmermann/TradeSystem#524]
i don`t know how to reproduce it.

warn:
```[18:58:15 WARN]: [TradeSystem] Task #982 for TradeSystem v2.5.3 generated an exception
java.lang.NullPointerException: Could not find a button at slot=16
        at de.codingair.tradesystem.lib.codingapi.player.gui.inventory.v2.Page.updateItem(Page.java:82) ~[?:?]
        at de.codingair.tradesystem.spigot.trade.gui.editor.utils.ItemStackEnterGUI$1.lambda$onClose$0(ItemStackEnterGUI.java:55) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PandaSpigot-"858ab0f"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-"858ab0f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:890) ~[patched_1.8.8.jar:git-PandaSpigot-"858ab0f"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-"858ab0f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-"858ab0f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-"858ab0f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-"858ab0f"]
        at java.lang.Thread.run(Thread.java:842) [?:?]```

**Comment by erikzimmermann** [comment]
Did you modify the layout in the file (layouts.yml)?

**Comment by erikzimmermann** [comment]
Stale.
