### ISSUE TITLE
RecipientId is sometimes null

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/TradeSystem#537]
**Describe the bug**
```
[10:52:42 INFO]: got result: INCOMPATIBLE (@survival-new)
[10:52:42 ERROR]: java.lang.IllegalStateException: RecipientId is null
[10:52:42 ERROR]:       at de.codingair.tradesystem.proxy.packets.TradeInvitePacket$ResultPacket.getRecipientId(TradeInvitePacket.java:167)
[10:52:42 ERROR]:       at de.codingair.tradesystem.proxy.core.handlers.TradeInvitePacketHandler.lambda$response$0(TradeInvitePacketHandler.java:46)
[10:52:42 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[10:52:42 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[10:52:42 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[10:52:42 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[10:52:42 ERROR]:       at de.codingair.tradesystem.lib.packetmanagement.DataHandler.receiveResponse(DataHandler.java:215)
[10:52:42 ERROR]:       at de.codingair.tradesystem.lib.packetmanagement.DataHandler.receive(DataHandler.java:143)
[10:52:42 ERROR]:       at de.codingair.tradesystem.proxy.velocity.utils.VelocityHandler.onPluginMessage(VelocityHandler.java:46)
[10:52:42 ERROR]:       at de.codingair.tradesystem.proxy.velocity.utils.Lmbda$120.execute(Unknown Source)
[10:52:42 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[10:52:42 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[10:52:42 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[10:52:42 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:52:42 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:52:42 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:840)
```

**To Reproduce**
"I have everything fine, in fact the plugin and the synchronization works great, but from time to time what I reported happens"

**Expected behavior**

**Screenshots**

**Additional context**
Tradesystem 2.5.3
TradeProxy 2.5.0

**Discord contact**: nolberh

**Comment by erikzimmermann** [comment]
Possible plugin channel attack which is fixed.
