### ISSUE TITLE
java.lang.NoClassDefFoundError: 1.20.4 support

### ISSUE THREAD

**Issue by daniel-skopek** [erikzimmermann/TradeSystem#539]
After compiled plugin from the source, the plugin won't start on 1.20.4. Is support for this version removed?

Error: https://pastebin.com/raw/fUne3ZKQ

**Comment by krouskystepan** [comment]
I have similar problem 

```
02:26:34[ERROR] Error occurred while disabling TradeSystem v2.5.3
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.getOwner()" because "this.tickerTimer" is null
at TradeSystem_v2.5.3.jar/de.codingair.tradesystem.lib.codingapi.API.removePlugin(API.java:132) ~[TradeSystem_v2.5.3.jar:?]
at TradeSystem_v2.5.3.jar/de.codingair.tradesystem.lib.codingapi.API.onDisable(API.java:71) ~[TradeSystem_v2.5.3.jar:?]
at TradeSystem_v2.5.3.jar/de.codingair.tradesystem.spigot.TradeSystem.onDisable(TradeSystem.java:133) ~[TradeSystem_v2.5.3.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2221-847719c]
at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by erikzimmermann** [comment]
Hi, @daniel-skopek. Which server type and version do you use? I just tested the hotfix 4 on paper 1.20.6, 1.20.4 and spigot 1.8.8 and everything works fine...
