### ISSUE TITLE
console error with CMI (maybe plugin conflict)  

### ISSUE THREAD

**Issue by Lia-LV** [erikzimmermann/TradeSystem#543]
**Describe the bug**
Console error when I open coin trade(anvil inventory)
( with Purpur 1.20.6, CMI 9.7.3.1, TradeSystem 2.5.3 Hotfix-4 )

**To Reproduce**
1. Open Trade with players
2. Open Coin Trade(anvil inventory)
3. See console error

**Expected behavior**
It doesn't affect for users as far as I think, but console gets dirty.

**Additional context**
```
[15:43:22 ERROR]: Could not pass event PrepareAnvilEvent to CMI v9.7.3.1
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
        at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at CMI-9.7.3.1.jar/com.Zrips.CMI.CustomEventTrigers.AnvilLstener.onItemRepair(AnvilLstener.java:147) ~[CMI-9.7.3.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor398.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2228-7708a4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1803) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.world.inventory.ItemCombinerMenu.slotsChanged(ItemCombinerMenu.java:114) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.world.inventory.ItemCombinerMenu$3.setChanged(ItemCombinerMenu.java:104) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.world.SimpleContainer.setItem(SimpleContainer.java:226) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at org.bukkit.craftbukkit.inventory.CraftResultInventory.setItem(CraftResultInventory.java:37) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at TradeSystem_v2.5.3_Hotfix-4.jar/de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI.open(AnvilGUI.java:283) ~[TradeSystem_v2.5.3_Hotfix-4.jar:?]
        at TradeSystem_v2.5.3_Hotfix-4.jar/de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI.openAnvil(AnvilGUI.java:139) ~[TradeSystem_v2.5.3_Hotfix-4.jar:?]
        at TradeSystem_v2.5.3_Hotfix-4.jar/de.codingair.tradesystem.lib.codingapi.player.gui.inventory.v2.buttons.AnvilButton.open(AnvilButton.java:20) ~[TradeSystem_v2.5.3_Hotfix-4.jar:?]
        at TradeSystem_v2.5.3_Hotfix-4.jar/de.codingair.tradesystem.lib.codingapi.player.gui.inventory.v2.GUIListener.onClick(GUIListener.java:61) ~[TradeSystem_v2.5.3_Hotfix-4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1340.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2228-7708a4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3260) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1638) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2228-7708a4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Discord contact**: lia_lv

**Comment by erikzimmermann** [comment]
Probably an issue with CMI and not TradeSystem. Right now, I would'nt know what I should change to solve this...
