### ISSUE TITLE
Issue with Multi-Server Trading in TradeSystem v2.6.0

### ISSUE THREAD

**Issue by AhmHkn0** [erikzimmermann/TradeSystem#549]
I'm currently using TradeSystem v2.6.0 and TradeProxy v2.6.0 plugins. The trading system works fine on a single server, but I encounter an error when attempting to trade across multiple servers.

Here is the error log:
```
[05:32:24 WARN]: [TradeSystem] Plugin TradeSystem v2.6.0 generated an exception whilst handling plugin message
de.codingair.tradesystem.lib.packetmanagement.exceptions.NoHandlerException: Cannot handle a packet without a handler: class de.codingair.tradesystem.proxy.packets.TradeInvitePacket
        at de.codingair.tradesystem.lib.packetmanagement.DataHandler.formHandler(DataHandler.java:109) ~[?:?]
        at de.codingair.tradesystem.lib.packetmanagement.DataHandler.receive(DataHandler.java:147) ~[?:?]
        at de.codingair.tradesystem.lib.packetmanagement.variants.bytestream.OneWayStreamDataHandler.receive(OneWayStreamDataHandler.java:63) ~[?:?]
        at de.codingair.tradesystem.spigot.transfer.SpigotHandler.onPluginMessageReceived(SpigotHandler.java:69) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3236) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:842) [?:?]
```

**Discord contact**: ahmhkn#0000

**Comment by erikzimmermann** [comment]
This was fixed in 2.6.1
