### ISSUE TITLE
1.21.1 Support

### ISSUE THREAD

**Issue by jbj338033** [erikzimmermann/TradeSystem#550]
1|survival  | [06:36:07 ERROR]: Error occurred while enabling TradeSystem v2.6.0 (Is it up to date?)
1|survival  | de.codingair.tradesystem.lib.codingapi.nms.NmsCheckError: Could not initialize class: de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI. Version=v1_21, Type=Paper, Bukkit='1.21.1-2285-abf2f21 (MC: 1.21.1)'
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:63) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:55) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.testInternalApi(NmsCheck.java:44) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:53) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.spigot.TradeSystem.checkNms(TradeSystem.java:196) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.spigot.TradeSystem.onEnable(TradeSystem.java:102) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
1|survival  |   at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
1|survival  |   at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
1|survival  |   at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
1|survival  | Caused by: java.lang.ExceptionInInitializerError
1|survival  |   at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
1|survival  |   at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
1|survival  |   at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
1|survival  |   at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
1|survival  |   at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200) ~[?:?]
1|survival  |   at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
1|survival  |   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
1|survival  |   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:85) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   ... 17 more
1|survival  | Caused by: java.lang.IllegalStateException: Unable to find method getBukkitView (null).
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:187) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI.<clinit>(AnvilGUI.java:79) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
1|survival  |   at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
1|survival  |   at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
1|survival  |   at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
1|survival  |   at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200) ~[?:?]
1|survival  |   at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
1|survival  |   at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
1|survival  |   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:85) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[TradeSystem_v2.6.0.jar:?]
1|survival  |   ... 17 more
1|survival  | [06:36:07 INFO]: [TradeSystem] Disabling TradeSystem v2.6.0

**Comment by Jorc0** [comment]
```
[07:28:41 ERROR]: Error occurred while enabling TradeSystem v2.6.0 (Is it up to date?)
de.codingair.tradesystem.lib.codingapi.nms.NmsCheckError: Could not initialize class: de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI. Version=v1_21, Type=Paper, Bukkit='1.21.1-2285-abf2f21 (MC: 1.21.1)'
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:63) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:55) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.testInternalApi(NmsCheck.java:44) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:53) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.spigot.TradeSystem.checkNms(TradeSystem.java:196) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.spigot.TradeSystem.onEnable(TradeSystem.java:102) ~[TradeSystem_v2.6.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2285-abf2f21]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:85) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[TradeSystem_v2.6.0.jar:?]
        ... 17 more
Caused by: java.lang.IllegalStateException: Unable to find method getBukkitView (null).
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:187) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI.<clinit>(AnvilGUI.java:79) ~[TradeSystem_v2.6.0.jar:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:85) ~[TradeSystem_v2.6.0.jar:?]
        at TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[TradeSystem_v2.6.0.jar:?]
        ... 17 more
[07:28:41 INFO]: [TradeSystem] Disabling TradeSystem v2.6.0
[07:28:41 ERROR]: [TradeSystem] This Minecraft version does not seem to be supported yet. Please contact the author with the given error above.
```
