### ISSUE TITLE
Are you sure the plugin supports 1.21?

### ISSUE THREAD

**Issue by BBDL233** [erikzimmermann/TradeSystem#553]
The plugin cannot start correctly, this is a report from the console

[11:28:11 INFO]: [TradeSystem] Enabling TradeSystem v2.6.0
[11:28:11 ERROR]: Error occurred while enabling TradeSystem v2.6.0 (Is it up to date?)
de.codingair.tradesystem.lib.codingapi.nms.NmsCheckError: Could not initialize class: de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI. Version=v1_21, Type=Paper, Bukkit='1.21-130-b1b5d4c (MC: 1.21)'
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:63) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:55) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.testInternalApi(NmsCheck.java:44) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:53) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.spigot.TradeSystem.checkNms(TradeSystem.java:196) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.spigot.TradeSystem.onEnable(TradeSystem.java:102) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200) ~[?:?]
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:85) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        ... 17 more
Caused by: java.lang.IllegalStateException: Unable to find method getBukkitView (null).
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:187) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getMethod(IReflection.java:185) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI.<clinit>(AnvilGUI.java:79) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200) ~[?:?]
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:85) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        at [T][1.8-1.21][交易]TradeSystem_v2.6.0.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[[T][1.8-1.21][交易]TradeSystem_v2.6.0.jar:?]
        ... 17 more
[11:28:11 INFO]: [TradeSystem] Disabling TradeSystem v2.6.0
[11:28:11 ERROR]: [TradeSystem] This Minecraft version does not seem to be supported yet. Please contact the author with the given error above.
[11:28:11 ERROR]: [TradeSystem] Here's an invitation to the discord for support: https://discord.gg/DxKMcGjQbp

**Comment by GG-MD** [comment]
and
https://pastebin.com/raw/y5jLwyUb
