### ISSUE TITLE
Plugins not working in 1.21

### ISSUE THREAD

**Issue by ZherKing** [erikzimmermann/TradeSystem#558]
**Describe the bug**
When i first use the plugin,Plugins not working in 1.21

**To Reproduce**
None
**Expected behavior**

working in the server

**Screenshots**
None

**Additional context**

Paper 1.21-130 plugin version 2.6.2

```
[00:52:20 INFO]: [TradeSystem] Enabling TradeSystem v2.6.2
[00:52:20 ERROR]: Error occurred while enabling TradeSystem v2.6.2 (Is it up to date?)
de.codingair.tradesystem.lib.codingapi.nms.NmsCheckError: Could not initialize class: de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI. Version=1.21.0, Type=Paper, Bukkit='1.21-106-3a47518 (MC: 1.21)'
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:63) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:55) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.testInternalApi(NmsCheck.java:44) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:53) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.spigot.TradeSystem.checkNms(TradeSystem.java:196) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.spigot.TradeSystem.onEnable(TradeSystem.java:102) ~[TradeSystem_v2.6.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-106-3a47518]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:173) ~[?:?]
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:83) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[TradeSystem_v2.6.2.jar:?]
        ... 17 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.inventory.view.CraftAnvilView
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getClass(IReflection.java:71) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getClass(IReflection.java:63) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI.<clinit>(AnvilGUI.java:60) ~[TradeSystem_v2.6.2.jar:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:173) ~[?:?]
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:83) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[TradeSystem_v2.6.2.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.inventory.view.CraftAnvilView
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.jar:1.21-106-3a47518]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getClass(IReflection.java:69) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getClass(IReflection.java:63) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.player.gui.anvil.AnvilGUI.<clinit>(AnvilGUI.java:60) ~[TradeSystem_v2.6.2.jar:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:340) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:173) ~[?:?]
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.runNmsLoader(NmsCheck.java:83) ~[TradeSystem_v2.6.2.jar:?]
        at TradeSystem_v2.6.2.jar/de.codingair.tradesystem.lib.codingapi.nms.NmsCheck.test(NmsCheck.java:61) ~[TradeSystem_v2.6.2.jar:?]
        ... 17 more
[00:52:20 INFO]: [TradeSystem] Disabling TradeSystem v2.6.2
[00:52:20 ERROR]: [TradeSystem] This Minecraft version appears to be unsupported. Ensure your server .jar file is up to date. If it is, please contact the author with the error message above.
[00:52:20 ERROR]: [TradeSystem] Here's an invitation to the discord for support: https://discord.gg/DxKMcGjQbp
```
**Discord contact**: [<name>#<id>](https://discord.com/channels/578230584871092235/585916390083526796/1281660599243116706)

**Comment by erikzimmermann** [comment]
Hey, you'll need to update the server and the plugin to the most recent build. This has already been fixed.
