### ISSUE TITLE
Trade Command Not Working

### ISSUE THREAD

**Issue by xsorencoolx** [erikzimmermann/TradeSystem#561]
on last version trade command not working and i saw error on console even on v2.6.2 without hotfix
[10:19:30 ERROR]: Error occurred while disabling TradeSystem v2.6.2_Hotfix-1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.codingair.tradesystem.spigot.commands.TradeCMD.unregister()" because "this.tradeCMD" is null
        at de.codingair.tradesystem.spigot.TradeSystem.lambda$onDisable$1(TradeSystem.java:151) ~[TradeSystem_v2.6.2_Hotfix-1.jar:?]
        at de.codingair.tradesystem.spigot.TradeSystem.printConsoleInfo(TradeSystem.java:185) ~[TradeSystem_v2.6.2_Hotfix-1.jar:?]
        at de.codingair.tradesystem.spigot.TradeSystem.onDisable(TradeSystem.java:148) ~[TradeSystem_v2.6.2_Hotfix-1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by AlexanderMandera** [comment]
This log message alone does not help identifying the issue. There is most likely another error message before that caused this issue. Please provide the full console log.
