### ISSUE TITLE
TradeSystem error - InventoryClickEvent to TradeSystem v2.6.3

### ISSUE THREAD

**Issue by UnitedCraft** [erikzimmermann/TradeSystem#570]
**Describe the bug**
in unexplained situations an error appears and players who had the GUI open and after placing items in this GUI simply disappeared forever and the error below appeared.

```
[2024-12-08 18:39:08.842] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TradeSystem v2.6.3
java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4227) ~[?:?]
	at net.minecraft.core.NonNullList.get(NonNullList.java:44) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.world.level.block.entity.BaseContainerBlockEntity.getItem(BaseContainerBlockEntity.java:139) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.getItem(RandomizableContainerBlockEntity.java:57) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at org.bukkit.craftbukkit.inventory.CraftInventory.getItem(CraftInventory.java:52) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at TradeSystem-1.21.3.jar/de.codingair.tradesystem.spigot.trade.gui.InventoryMask$1.getItem(InventoryMask.java:56) ~[TradeSystem-1.21.3.jar:?]
	at TradeSystem-1.21.3.jar/de.codingair.tradesystem.spigot.trade.gui.Actions.handleMove(Actions.java:567) ~[TradeSystem-1.21.3.jar:?]
	at TradeSystem-1.21.3.jar/de.codingair.tradesystem.spigot.trade.gui.Actions.projectResult(Actions.java:182) ~[TradeSystem-1.21.3.jar:?]
	at TradeSystem-1.21.3.jar/de.codingair.tradesystem.spigot.trade.gui.TradeGUIListener.onClick(TradeGUIListener.java:98) ~[TradeSystem-1.21.3.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor590.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kyan-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[kyan-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kyan-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:57) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[kyan-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3338) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1625) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1602) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1595) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1552) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1392) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:345) ~[kyan-1.21.3.jar:1.21.3-DEV-5e9bf77]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

**Comment by erikzimmermann** [comment]
This issue seems to be very rare and hard to reproduce. When this happens, all entered items are lost. Appearantly, one of the players was trading a named shulker box.

**Comment by zuhaz** [comment]
I'm also facing the same issue.
