### ISSUE TITLE
Tradesystem 2.6.2-hotfix-2 not working for 1.20.4

### ISSUE THREAD

**Issue by djoey123** [erikzimmermann/TradeSystem#571]
**Describe the bug**
When server is started plugin throws an exception:
![afbeelding](https://github.com/user-attachments/assets/b73c9f3a-eef4-4c25-b946-c741c968f3cb)

`java.lang.ExceptionInInitializerError: null
        at de.codingair.tradesystem.spigot.trade.gui.layout.registration.IconHandler.registerBasic(IconHandler.java:126) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.spigot.trade.gui.layout.registration.IconHandler.registerDefault(IconHandler.java:45) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.spigot.trade.gui.layout.registration.IconHandler.access$000(IconHandler.java:25) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.spigot.trade.gui.layout.registration.IconHandler$1.registerDefault(IconHandler.java:33) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.spigot.TradeSystem.lambda$onEnable$0(TradeSystem.java:111) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at com.github.Anon8281.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTask$0(FoliaScheduler.java:49) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[paper-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[paper-1.20.4.jar:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1649) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Unable to find field profile (null).
        at de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getField(IReflection.java:283) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getField(IReflection.java:281) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.lib.codingapi.server.reflections.IReflection.getField(IReflection.java:225) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.lib.codingapi.player.data.GameProfileUtils.extractSkinId(GameProfileUtils.java:53) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:131) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.lib.codingapi.tools.items.ItemBuilder.<init>(ItemBuilder.java:68) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        at de.codingair.tradesystem.spigot.trade.gui.layout.registration.Type.<clinit>(Type.java:13) ~[TradeSystem_v2.6.2_Hotfix-2.jar:?]
        ... 14 more`

**Expected behavior**
Server starting normally 

**Additional context**
velocity: 3.4.0
Paper-497 (1.20.4)
Geyser: Build #739
Tradesystem: 2.6.2-hotfix-2

**Discord contact**: JustDjoey

**Comment by djoey123** [comment]
latest commit fixes this error.

Sadly ther is an new error:

![afbeelding](https://github.com/user-attachments/assets/1464420d-ff2a-485d-b96c-a6f225e92796)

**Comment by djoey123** [comment]
Sorry, first error is still existing.

**Comment by erikzimmermann** [comment]
Fixed.
